apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-controller
  namespace: my-controller
  labels:
    app:  my-controller
spec:
  selector:
    matchLabels:
      app: my-controller
  replicas: 2
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app:  my-controller
    spec:
      serviceAccountName: my-controller-serviceaccount
      restartPolicy: Always
      containers:
      - name:  my-controller
        image:  'my-controller:0.0.0-dev'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name:  my-controller
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
