apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-controller:controller:namespace-controller
  labels:
    app: my-controller
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - watch
      - list
      - update
      - patch
  - apiGroups:
      - 'coordination.k8s.io'
    resources:
      - leases
    verbs:
      - '*'
